.\" SPDX-FileCopyrightText: 2022 Andrea Pappacoda <andrea@pappacoda.it>
.\" SPDX-License-Identifier: GPL-2.0-or-later
.Dd 2022-09-01
.Dt YUZU 1
.Os
.
.Sh NAME
.Nm yuzu
.Nd Nintendo Switch Emulator
.
.Sh SYNOPSIS
.Nm
.
.Sh DESCRIPTION
.Nm
is an experimental open-source emulator for the Nintendo Switch from the
creators of Citra.
.Pp
It is written in C++ with portability in mind, with builds actively maintained
for Windows and Linux.
.
.Sh SEE ALSO
.Xr yuzu-cmd 1
.Xr yuzu-room 1
.
.Sh AUTHORS
.An -nosplit
.Nm
was written by the
.An yuzu Emulator Project .
.Pp
This manual page was written by
.An Andrea Pappacoda Aq Mt andrea@pappacoda.it
for the Debian project (and may be used by others).
